$id: >-
  http://qubership.org/schemas/product/qip/element/circuit-breaker-configuration-2.schema.yaml
$schema: http://json-schema.org/draft-07/schema
type: object
allOf:
  - type: object
    allOf:
      - type: object
        title: Common Entity Properties
        properties:
          id:
            type: string
            title: Identifier
          name:
            type: string
            title: Name
        required:
          - id
          - name
      - type: object
        title: Entity with description
        properties:
          description:
            type: string
            title: Description
      - type: object
        properties:
          swimlaneId:
            type: string
  - $schema: http://json-schema.org/draft-07/schema
    type: object
    title: Container element
    properties:
      children:
        type: array
        title: Child elements
        items:
          type: object
title: Circuit Breaker Configuration
properties:
  type:
    type: string
    const: circuit-breaker-configuration-2
  properties:
    type: object
    properties:
      automaticTransitionFromOpenToHalfOpenEnabled:
        type: boolean
        title: Automatic transition from open to half open state
        description: >
          Enables automatic transition from OPEN to HALF_OPEN state once the
          "Wait duration in open state" has passed
        default: false
      failureRateThreshold:
        allOf:
          - &ref_0
            oneOf:
              - type: integer
                minimum: 0
              - type: string
                pattern: ^[0-9]+$
              - type: string
                pattern: ^#\{[a-zA-Z0-9:._-]+\}$
        title: Failure rate threshold (%)
        description: >
          Configures the failure rate threshold in percentage. If the failure
          rate is equal or greater than the threshold the CircuitBreaker
          transitions to open and starts short-circuiting calls. The threshold
          must be greater than 0 and not greater than 100.
        default: 50
      minimumNumberOfCalls:
        allOf:
          - *ref_0
        title: Minimum number of calls
        description: >
          Configures the minimum number of calls which are required (per sliding
          window period) before the CircuitBreaker can calculate the error rate.
          For example, if "Minimum number of calls" is 10, then at least 10
          calls must be recorded, before the failure rate can be calculated. If
          only 9 calls have been recorded the CircuitBreaker will not transition
          to open even if all 9 calls have failed.
        default: 100
      permittedNumberOfCallsInHalfOpenState:
        allOf:
          - *ref_0
        title: Permitted number of calls in half open state
        description: >
          Configures the number of permitted calls when the CircuitBreaker is
          half open. The size must be greater than 0
        default: 10
      slidingWindowSize:
        allOf:
          - *ref_0
        title: Sliding window size
        description: >
          Configures the size of the sliding window which is used to record the
          outcome of calls when the CircuitBreaker is closed. Sliding window can
          either be count-based or time-based. If slidingWindowType is
          COUNT_BASED, the last slidingWindowSize calls are recorded and
          aggregated. If slidingWindowType is TIME_BASED, the calls of the last
          slidingWindowSize seconds are recorded and aggregated. If the "Sliding
          window type" is COUNT_BASED, the "Minimum number of calls" cannot be
          greater than "Sliding window size".
        default: 100
      slidingWindowType:
        enum:
          - COUNT_BASED
          - TIME_BASED
        title: Sliding window type
        default: COUNT_BASED
      slowCallDurationThreshold:
        allOf:
          - *ref_0
        title: Slow call duration threshold (s)
        description: >
          Configures the duration threshold (seconds) above which calls are
          considered as slow and increase the slow calls percentage.
        default: 60
      slowCallRateThreshold:
        allOf:
          - *ref_0
        title: Slow call rate threshold (%)
        description: >
          Configures a threshold in percentage. The CircuitBreaker considers a
          call as slow when the call duration is greater than "Slow call
          duration threshold" duration. When the percentage of slow calls is
          equal or greater the threshold, the CircuitBreaker transitions to open
          and starts short-circuiting calls.
        default: 100
      waitDurationInOpenState:
        allOf:
          - *ref_0
        title: Wait duration in open state (s)
        description: >
          Configures the wait duration (in seconds) which specifies how long the
          CircuitBreaker should stay open, before it switches to half open.
        default: 60
    additionalProperties: false
required:
  - properties
  - type
