import React from "react";
import type { AntdIconProps } from "@ant-design/icons/lib/components/AntdIcon";
import {
  DeleteOutlined,
  PlusOutlined,
  InboxOutlined,
  MoreOutlined,
  SaveOutlined,
  UserOutlined,
  ExclamationCircleOutlined,
  FileTextOutlined,
  RollbackOutlined,
  SendOutlined,
  LeftOutlined,
  RightOutlined,
  DoubleLeftOutlined,
  DoubleRightOutlined,
  TableOutlined,
  CloudUploadOutlined,
  CloudDownloadOutlined,
  LockOutlined,
  DownOutlined,
  UpOutlined,
  DesktopOutlined,
  LinkOutlined,
  DownloadOutlined,
  ExportOutlined,
  StopOutlined,
  CopyOutlined,
  CloudOutlined,
  AppstoreOutlined,
  SettingOutlined,
  BellOutlined,
  RedoOutlined,
  CaretRightFilled,
  CaretDownFilled,
  UnorderedListOutlined,
  AuditOutlined,
  SnippetsOutlined,
  CodeOutlined,
  EditOutlined,
  CheckOutlined,
  QuestionCircleOutlined,
  CloseOutlined,
  CloseCircleOutlined,
  MinusOutlined,
  ExpandOutlined,
  RotateRightOutlined,
  ClearOutlined,
  EllipsisOutlined,
  PlusCircleOutlined,
  FileMarkdownOutlined,
  ClusterOutlined,
  GlobalOutlined,
  HomeOutlined,
  FilterOutlined,
  CarryOutOutlined,
  FileAddOutlined,
  FileOutlined,
  FolderAddOutlined,
  FolderOutlined,
  ApartmentOutlined,
  ApiOutlined,
  GroupOutlined,
  DeploymentUnitOutlined,
  EyeInvisibleOutlined,
  FileDoneOutlined,
  FileUnknownOutlined,
  QuestionOutlined,
  RadarChartOutlined,
  SolutionOutlined,
  ColumnHeightOutlined,
  VerticalAlignMiddleOutlined,
  FolderOpenFilled,
  FlagOutlined,
  FileSearchOutlined,
  UploadOutlined,
  LayoutOutlined,
  NodeIndexOutlined,
  BlockOutlined,
  ProfileOutlined,
  ReloadOutlined,
  BranchesOutlined,
  ForkOutlined,
  NodeCollapseOutlined,
  NodeExpandOutlined,
  MailOutlined,
  CloudServerOutlined,
  FileSyncOutlined,
  DiffOutlined,
  ShareAltOutlined,
  InteractionOutlined,
  ScheduleOutlined,
  LoginOutlined,
  LogoutOutlined,
  StepForwardOutlined,
  StepBackwardOutlined,
  PullRequestOutlined,
  SisternodeOutlined,
  CheckCircleOutlined,
  DeliveredProcedureOutlined,
  DeleteRowOutlined,
  DatabaseOutlined,
  ContainerOutlined,
  FullscreenOutlined,
  FullscreenExitOutlined,
  BulbOutlined,
  BarChartOutlined,
  ToolOutlined,
  MenuUnfoldOutlined,
  InfoCircleOutlined,
  HddOutlined,
  CloudSyncOutlined,
  ImportOutlined,
  ShrinkOutlined,
  ArrowsAltOutlined,
  CheckSquareOutlined,
  WarningOutlined,
  InsertRowRightOutlined,
  InsertRowLeftOutlined,
  CommentOutlined,
  PaperClipOutlined,
  MessageOutlined,
} from "@ant-design/icons";

/**
 * Дефолтный логотип шапки (текст QIP). Override: configure({ icons: { logo: … } }).
 * Устаревшее имя ключа в конфиге: `qip` — см. merge в IconProvider.
 */
const QIP_WORDMARK_FONT_FAMILY =
  '"Trebuchet MS", "Lucida Sans Unicode", "Segoe UI", sans-serif';

const DefaultNavLogoIcon: React.FC<AntdIconProps> = ({ style, className }) => (
  <svg
    xmlns="http://www.w3.org/2000/svg"
    viewBox="0 0 40 18"
    fill="none"
    preserveAspectRatio="xMidYMid meet"
    style={style}
    className={className}
  >
    <title>QIP</title>
    <text
      x="20"
      y="9"
      textAnchor="middle"
      dominantBaseline="central"
      fill="currentColor"
      fontFamily={QIP_WORDMARK_FONT_FAMILY}
      fontSize="20"
      fontWeight="700"
      letterSpacing="-0.06em"
    >
      QIP
    </text>
  </svg>
);

export const commonIcons = {
  plus: PlusOutlined,
  delete: DeleteOutlined,
  inbox: InboxOutlined,
  more: MoreOutlined,
  save: SaveOutlined,
  sessions: UserOutlined,
  exclamationCircle: ExclamationCircleOutlined,
  fileText: FileTextOutlined,
  rollback: RollbackOutlined,
  send: SendOutlined,
  left: LeftOutlined,
  right: RightOutlined,
  doubleLeft: DoubleLeftOutlined,
  doubleRight: DoubleRightOutlined,
  table: TableOutlined,
  cloudUpload: CloudUploadOutlined,
  cloudDownload: CloudDownloadOutlined,
  lock: LockOutlined,
  down: DownOutlined,
  up: UpOutlined,
  desktop: DesktopOutlined,
  link: LinkOutlined,
  download: DownloadOutlined,
  export: ExportOutlined,
  stop: StopOutlined,
  copy: CopyOutlined,
  cloud: CloudOutlined,
  appstore: AppstoreOutlined,
  settings: SettingOutlined,
  bell: BellOutlined,
  redo: RedoOutlined,
  caretRightFilled: CaretRightFilled,
  caretDownFilled: CaretDownFilled,
  unorderedList: UnorderedListOutlined,
  audit: AuditOutlined,
  snippets: SnippetsOutlined,
  code: CodeOutlined,
  edit: EditOutlined,
  check: CheckOutlined,
  questionCircle: QuestionCircleOutlined,
  close: CloseOutlined,
  closeCircle: CloseCircleOutlined,
  minus: MinusOutlined,
  expand: ExpandOutlined,
  expandAll: ArrowsAltOutlined,
  collapseAll: ShrinkOutlined,
  rotateRight: RotateRightOutlined,
  clear: ClearOutlined,
  ellipsis: EllipsisOutlined,
  plusCircle: PlusCircleOutlined,
  fileMarkdown: FileMarkdownOutlined,
  cluster: ClusterOutlined,
  global: GlobalOutlined,
  home: HomeOutlined,
  logo: DefaultNavLogoIcon,
  filter: FilterOutlined,
  carryOut: CarryOutOutlined,
  fileAdd: FileAddOutlined,
  file: FileOutlined,
  folderAdd: FolderAddOutlined,
  folder: FolderOutlined,
  folderOpenFilled: FolderOpenFilled,
  apartment: ApartmentOutlined,
  api: ApiOutlined,
  group: GroupOutlined,
  deploymentUnit: DeploymentUnitOutlined,
  eyeInvisible: EyeInvisibleOutlined,
  fileDone: FileDoneOutlined,
  fileUnknown: FileUnknownOutlined,
  question: QuestionOutlined,
  radarChart: RadarChartOutlined,
  solution: SolutionOutlined,
  columnHeight: ColumnHeightOutlined,
  verticalAlignMiddle: VerticalAlignMiddleOutlined,
  database: DatabaseOutlined,
  fullscreen: FullscreenOutlined,
  fullscreenExit: FullscreenExitOutlined,
  bulb: BulbOutlined,
  barChart: BarChartOutlined,
  tool: ToolOutlined,
  rightPanel: InsertRowRightOutlined,
  leftPanel: InsertRowLeftOutlined,
  block: BlockOutlined,
  menuUnfold: MenuUnfoldOutlined,
  info: InfoCircleOutlined,
  liveExchanges: NodeIndexOutlined,
  domains: HddOutlined,
  accessControl: LockOutlined,
  refresh: RedoOutlined,
  cloudSync: CloudSyncOutlined,
  importInstructions: ImportOutlined,
  warning: WarningOutlined,
  checkSquare: CheckSquareOutlined,
  mcp: MessageOutlined,
  comment: CommentOutlined,
  paperClip: PaperClipOutlined,
};

export const elementIcons = {
  checkpoint: FlagOutlined,
  "file-read": FileSearchOutlined,
  "file-write": FileTextOutlined,
  "sftp-download": DownloadOutlined,
  "sftp-upload": UploadOutlined,
  swimlane: LayoutOutlined,
  "chain-call-2": NodeIndexOutlined,
  "circuit-breaker-2": ApiOutlined,
  condition: BlockOutlined,
  "log-record": ProfileOutlined,
  "loop-2": ReloadOutlined,
  reuse: NodeCollapseOutlined,
  "reuse-reference": NodeExpandOutlined,
  "split-2": ForkOutlined,
  "split-async-2": BranchesOutlined,
  "try-catch-finally-2": DeploymentUnitOutlined,
  "graphql-sender": RadarChartOutlined,
  "http-sender": LogoutOutlined,
  "kafka-sender-2": CloudDownloadOutlined,
  "pubsub-sender": CloudDownloadOutlined,
  "rabbitmq-sender-2": CloudDownloadOutlined,
  "mail-sender": MailOutlined,
  "service-call": ClusterOutlined,
  "context-storage": FileSyncOutlined,
  "header-modification": DiffOutlined,
  "mapper-2": ShareAltOutlined,
  script: CodeOutlined,
  xslt: FileTextOutlined,
  "kafka-trigger-2": CloudUploadOutlined,
  "pubsub-trigger": CloudUploadOutlined,
  "rabbitmq-trigger-2": CloudUploadOutlined,
  "async-api-trigger": CloudServerOutlined,
  "chain-trigger-2": InteractionOutlined,
  "quartz-scheduler": ScheduleOutlined,
  "sftp-trigger-2": FileAddOutlined,
  "http-trigger": LoginOutlined,
  if: StepForwardOutlined,
  else: StepBackwardOutlined,
  "main-split-element-2": GroupOutlined,
  "split-element-2": PullRequestOutlined,
  "async-split-element-2": SisternodeOutlined,
  "try-2": CheckCircleOutlined,
  "catch-2": CloseCircleOutlined,
  "finally-2": QuestionCircleOutlined,
  "circuit-breaker-configuration-2": DeliveredProcedureOutlined,
  "on-fallback-2": DeleteRowOutlined,
  container: ContainerOutlined,
};
