import { SelectProps } from "antd";

export type TableFilterType = 'string' | 'number' | 'date' | 'select' | 'multipleSelect';

export type TableFilterDropdownColumnItem = {
  name?: string;
  id?: string;
  type?: TableFilterType;
}

export type FilterModel = {
  columnOptions: SelectProps["options"];
  conditionOptions: SelectProps["options"];
  valueOptions: SelectProps["options"];
}

export enum FilterColumn {
  STATUS = 'STATUS',
  ENGINES = 'ENGINES',
  LOGGING = 'LOGGING',
  NAME = 'NAME',
  ID = 'ID',
  DESCRIPTION = 'DESCRIPTION',
  PATH = 'PATH',
  METHOD = 'METHOD',
  TOPIC = 'TOPIC',
  EXCHANGE = 'EXCHANGE',
  QUEUE = 'QUEUE',
  PROTOCOL = 'PROTOCOL',
  SERVICE_ID = 'SERVICE_ID',
  OPERATION = 'OPERATION',
  ENTITY_ID = 'ENTITY_ID',
  ENTITY_TYPE = 'ENTITY_TYPE',
  ENTITY_NAME = 'ENTITY_NAME',
  PARENT_ID = 'PARENT_ID',
  PARENT_NAME = 'PARENT_NAME',
  REQUEST_ID = 'REQUEST_ID',
  LABELS = 'LABELS',
  ENDPOINT = 'ENDPOINT',
  TYPE = 'TYPE',
  ROLES = 'ROLES',
  CHAIN = 'CHAIN',
  CHAIN_ID = 'CHAIN_ID',
  CHAIN_NAME = 'CHAIN_NAME',
  CHAIN_STATUS = 'CHAIN_STATUS',
  ELEMENT = 'ELEMENT',
  KEY = 'KEY',
  VALUE = 'VALUE',
  START_TIME = 'START_TIME',
  FINISH_TIME = 'FINISH_TIME',
  END_TIME = 'END_TIME',
  CREATED = 'CREATED',
  SPECIFICATION_GROUP = 'SPECIFICATION_GROUP',
  SPECIFICATION_VERSION = 'SPECIFICATION_VERSION',
  URL = 'URL',
  ACTION_TIME = 'ACTION_TIME',
  ELEMENT_ID = 'ELEMENT_ID',
  ELEMENT_NAME = 'ELEMENT_NAME',
  ELEMENT_TYPE = 'ELEMENT_TYPE',
  ELEMENT_PROPERTY_NAME = 'ELEMENT_PROPERTY_NAME',
  ELEMENT_PROPERTY_SOURCE = 'ELEMENT_PROPERTY_SOURCE',
  ELEMENT_PROPERTY_TYPE = 'ELEMENT_PROPERTY_TYPE',
  ELEMENT_PROPERTY_USAGE_TYPE = 'ELEMENT_PROPERTY_USAGE_TYPE',
  INITIATOR = 'INITIATOR',
  VALIDATION_SEVERITY = 'VALIDATION_SEVERITY',
  OVERRIDDEN_BY = 'OVERRIDDEN_BY',
  INSTRUCTION_ACTION = 'INSTRUCTION_ACTION',
  MODIFIED_WHEN = 'MODIFIED_WHEN',
  DOMAINS = 'DOMAINS',
}