---
env:
  browser: true
  es2021: true
  node: true

extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended

rules:
  n/no-missing-import: off
  n/no-unsupported-features/node-builtins: off
  react-hooks/exhaustive-deps: off
  react/react-in-jsx-scope: off
