---
env:
  browser: true
  es6: true

extends:
  - "eslint:recommended"
  - "plugin:react/recommended"
  - "plugin:@typescript-eslint/recommended"

parser: "@typescript-eslint/parser"

plugins:
  - "@typescript-eslint"

rules:
  no-undef: "warn"
  react/react-in-jsx-scope": "off"

globals:
  module: "writable"
