extends:
  - stylelint-config-standard

rules:
  # CSS Modules ≠ global CSS naming
  selector-class-pattern: null

  # :global(...) from CSS Modules
  selector-pseudo-class-no-unknown:
    - true
    - ignorePseudoClasses:
        - global
