// Auto-generated by scripts/compile-validators.mjs
// Do not edit manually

import type { ValidateFunction } from 'ajv';

export declare const asyncApiTrigger: ValidateFunction;
export declare const asyncSplitElement2: ValidateFunction;
export declare const catch2: ValidateFunction;
export declare const chainCall2: ValidateFunction;
export declare const chainTrigger2: ValidateFunction;
export declare const checkpoint: ValidateFunction;
export declare const circuitBreaker2: ValidateFunction;
export declare const circuitBreakerConfiguration2: ValidateFunction;
export declare const condition: ValidateFunction;
export declare const container: ValidateFunction;
export declare const contextStorage: ValidateFunction;
export declare const elseElement: ValidateFunction;
export declare const fileRead: ValidateFunction;
export declare const fileWrite: ValidateFunction;
export declare const finally2: ValidateFunction;
export declare const graphqlSender: ValidateFunction;
export declare const headerModification: ValidateFunction;
export declare const httpSender: ValidateFunction;
export declare const httpTrigger: ValidateFunction;
export declare const ifElement: ValidateFunction;
export declare const jmsSender: ValidateFunction;
export declare const jmsTrigger: ValidateFunction;
export declare const kafkaSender2: ValidateFunction;
export declare const kafkaTrigger2: ValidateFunction;
export declare const logRecord: ValidateFunction;
export declare const loop2: ValidateFunction;
export declare const mailSender: ValidateFunction;
export declare const mainSplitElement2: ValidateFunction;
export declare const mapper2: ValidateFunction;
export declare const onFallback2: ValidateFunction;
export declare const pubsubSender: ValidateFunction;
export declare const pubsubTrigger: ValidateFunction;
export declare const quartzScheduler: ValidateFunction;
export declare const rabbitmqSender2: ValidateFunction;
export declare const rabbitmqTrigger2: ValidateFunction;
export declare const reuseReference: ValidateFunction;
export declare const reuse: ValidateFunction;
export declare const script: ValidateFunction;
export declare const scsSender: ValidateFunction;
export declare const sdsTrigger: ValidateFunction;
export declare const serviceCall: ValidateFunction;
export declare const sftpDownload: ValidateFunction;
export declare const sftpTrigger2: ValidateFunction;
export declare const sftpUpload: ValidateFunction;
export declare const split2: ValidateFunction;
export declare const splitAsync2: ValidateFunction;
export declare const splitElement2: ValidateFunction;
export declare const swimlane: ValidateFunction;
export declare const try2: ValidateFunction;
export declare const tryCatchFinally2: ValidateFunction;
export declare const xslt: ValidateFunction;

export declare const validators: Record<string, ValidateFunction>;
